# Project Configuration

project:
  name: "IndoPopBase Analytics"
  version: "1.0.0"
  target_account: "IndoPopBase"

scraping:
  max_tweets: 1000
  max_mentions: 500
  since_date: "2024-01-01"
  update_frequency: "daily"  # daily, weekly
  
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  models_dir: "data/models"

preprocessing:
  remove_urls: true
  remove_mentions: false
  remove_hashtags: false
  lowercase: true
  remove_stopwords: true
  language: "indonesian"

models:
  sentiment:
    model_name: "indobert"
    threshold: 0.5
  engagement:
    features: ["hour", "day_of_week", "text_length", "hashtag_count"]
    model_type: "random_forest"

mlops:
  experiment_tracking: "mlflow"
  model_registry: true
  monitoring_enabled: true
  drift_threshold: 0.1
  retraining_schedule: "weekly"

dashboard:
  host: "0.0.0.0"
  port: 8501
  theme: "light"